apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: {{KUBE_NAMESPACE}}
    app.kubernetes.io/instance: {{CI_PROJECT_NAME}}
    app.kubernetes.io/part-of: {{DOMAIN_SOLUTION}}
    app.kubernetes.io/managed-by: {{DOMAIN}}
  name: {{KUBE_NAMESPACE}}
---
# Solution level Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
#  annotations:
# NOTE: THIS IS FOR GKE WORKLOAD IDENTITY IF NEEDED  
#    iam.gke.io/gcp-service-account: {{WORKLOAD_IDENTITY_SERVICE_ACCOUNT}}
# NOTE: THIS IS FOR AKS WORKLOAD IDENTITY IF NEEDED  
#    azure.workload.identity/client-id: {{WORKLOAD_IDENTITY_SERVICE_ACCOUNT}}
  name: "{{KUBE_NAMESPACE}}-sa"
  namespace: {{KUBE_NAMESPACE}}
---
# Secrets Reader for DAPR
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{KUBE_NAMESPACE}}-secret-reader"
  namespace: {{KUBE_NAMESPACE}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{KUBE_NAMESPACE}}-secret-reader-binding"
  namespace: {{KUBE_NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: "{{KUBE_NAMESPACE}}-sa"
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: "{{KUBE_NAMESPACE}}-secret-reader"
  apiGroup: rbac.authorization.k8s.io

